/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MarkStore;

import DManage.DataManager;
import DManage.Student;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Aman Nautiyal
 */
public class ViewFrame extends javax.swing.JFrame {

    /**
     * Creates new form ViewFrame
     */
    private DefaultTableModel mod;
    public static final String[] COLUMNS={"Roll Number","Name","Physics","Chemistry","Maths"};
    public ViewFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        resTable = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        rollTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        nameTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nameTxtKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 18)); // NOI18N
        jLabel1.setText("Roll Number:");

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 18)); // NOI18N
        jLabel2.setText("Name:");

        resTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(resTable);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null,null},
                {null, null, null, null,null},
                {null, null, null, null,null},
                {null, null, null, null,null}
            },
            new String [] {
                "Roll Number","Name","Physics","Chemistry","Maths"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        rollTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                rollTxtKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 879, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rollTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(54, 54, 54))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rollTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameTxtKeyReleased
        //System.out.println("Name Text Key typed");
        String str=nameTxt.getText();
        //System.out.println(str);
        try
        {
        mod=updateTableModel(str);
        }
        catch(Exception e)
        {
         System.out.println("Exception in nameTxtKeyReleased:"+e.getMessage());
        }
       jTable1.setModel(mod);
       jTable1.invalidate();
       /* ArrayList<Student> stlist;
        stlist=DataManager.getStudent(str);
        for (Student s : stlist) {
          resText.setText(resText.getText()+"\n"+s.getRollNumber()+"\t"+s.getName());
          for(int i=0;i<30-s.getName().length();i++)
              resText.setText(resText.getText()+" ");
         resText.setText(resText.getText()+ "\t\t\t\t"+s.getPhysics()+"\t"+s.getChemistry()+"\t"+s.getMaths());
        }*/
    }//GEN-LAST:event_nameTxtKeyReleased

    private void rollTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rollTxtKeyReleased
        //System.out.println("Roll Text Key typed");
        String str=rollTxt.getText();
        System.out.println(str);
        try
        {
           mod=updateTableModel(Integer.parseInt(str));
        }
        catch(Exception e)
        {
         System.out.println("Exception in nameTxtKeyReleased:"+e.getMessage());
        }

       jTable1.setModel(mod);
        jTable1.invalidate();
    }//GEN-LAST:event_rollTxtKeyReleased
    private DefaultTableModel updateTableModel(String str)
    {
     DefaultTableModel update=new DefaultTableModel(null, COLUMNS);
     ArrayList<Student> stlist;
        stlist=DataManager.getStudent(str);
        Vector row;
        
        for (Student s : stlist) {
          row=new Vector();
          row.add(s.getRollNumber());
          row.add(s.getName());
          row.add(s.getPhysics());
          row.add(s.getChemistry());
          row.add(s.getMaths());
          update.addRow(row);
        }
        return update;
    }
    private DefaultTableModel updateTableModel(int rol)
    {
     DefaultTableModel update=new DefaultTableModel(null, COLUMNS);
     ArrayList<Student> stlist;
        stlist=DataManager.getStudent(rol);
        Vector row;
        
        for (Student s : stlist) {
          row=new Vector();
          row.add(s.getRollNumber());
          row.add(s.getName());
          row.add(s.getPhysics());
          row.add(s.getChemistry());
          row.add(s.getMaths());
          update.addRow(row);
        }
        return update;
    }
    private DefaultTableModel updateAllTableModel()
    {
     DefaultTableModel update=new DefaultTableModel(null, COLUMNS);
     ArrayList<Student> stlist;
        stlist=DataManager.getAllStudents();
        Vector row;
        
        for (Student s : stlist) {
          row=new Vector();
          row.add(s.getRollNumber());
          row.add(s.getName());
          row.add(s.getPhysics());
          row.add(s.getChemistry());
          row.add(s.getMaths());
          update.addRow(row);
        }
        return update;
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JTable resTable;
    private javax.swing.JTextField rollTxt;
    // End of variables declaration//GEN-END:variables
}
